repository:
  name: codeclimate-editorconfig-demo
  description: a demo for CodeClimate EditorConfig Plugin
  topics: editorconfig, codeclimate, demo
  homepage: https://www.codeclimate.com
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  has_projects: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
